name: Deploy to EC2

on:
  push:
    branches:
      - main # Adjust to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Archive the build output
      - name: Archive build output
        run: tar -czf build.tar.gz dist

      # Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the artifact
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_ELASTIC_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no build.tar.gz $EC2_USER@$EC2_HOST:/home/ubuntu/thareeh-designs-backend
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/thareeh-designs-backend
            tar -xzf build.tar.gz
            npm install --production

            # Check if the process exists, if not start it
            if ! pm2 describe thareeh-backend > /dev/null; then
              pm2 start dist/server.js --name thareeh-backend
            else
              pm2 restart thareeh-backend
            fi

            # Save the process list for restart on reboot
            pm2 save
          EOF
